@startuml
title mac init

start

:start mac;
:uninstall os;
:erase volumes;
:install os;
:install brew;

  fork
    :install desktop tools;
  fork again
    :install java tools;
  end fork
  


:stop mac;

stop

@enduml
